apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'maven-publish'

android {
    namespace = "com.tealium.remotecommands.contentsquare"
    compileSdk 33

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 33

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'

        buildConfigField "String", "TEALIUM_CONTENTSQUARE_VERSION", "\"$tealium_contentsquare_version\""
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
            minifyEnabled false
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11
    }

    buildFeatures {
        buildConfig = true
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
            withJavadocJar()
        }
    }
}

publishing {
    publications {
        release(MavenPublication) {
            groupId 'com.tealium.remotecommands'
            artifactId 'contentsquare'
            version "$tealium_contentsquare_version"
            afterEvaluate {
                from components.release
            }
        }
    }
    // repositories {
    //     maven {
    //         url "s3://maven.tealiumiq.com/android/releases/"
    //         credentials(AwsCredentials) {
    //             // Dummy credentials provided in project's gradle.properties; these will be overridden by your global settings in ~/.gradle/gradle.properties
    //             accessKey AWS_ACCESS_KEY
    //             secretKey AWS_SECRET_KEY
    //             sessionToken AWS_SESSION_TOKEN
    //         }
    //     }
    // }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // Tealium dependencies
    api "com.tealium:remotecommands:1.0.3"
    
    // ContentSquare dependencies
    api "com.contentsquare.android:library$contentsquare_version"
    
    // Test dependencies
    testImplementation 'junit:junit:4.13.2'
    testImplementation "org.robolectric:robolectric:4.10.3"
    testImplementation "io.mockk:mockk:$mockk_version"
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}
